name: CI/CD to Cloud Run Jobspark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: jobspark
          service_account_key: ${{ secrets.GCP_SA_KEYS }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Login to Google Container Registry
        run: |
         gcloud auth configure-docker \ us-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/jobspark/jobspark-api:${{ github.sha }} .
          docker push gcr.io/jobspark/jobspark-api:${{ github.sha }}

      # Deploy the container to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy jobspark-api \
            --image gcr.io/jobspark/jobspark-api:${{ github.sha }} \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
