name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Cache Docker layers to speed up builds (optional)
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.docker/buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/jobspark-api .

    # Step 5: Authenticate with Google Cloud and push the Docker image to Google Container Registry
    - name: Push Docker image to Google Container Registry
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/jobspark-api

    # Step 6: Deploy the Docker image to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud auth activate-service-account --key-file <(echo ${{ secrets.GCP_SA_KEY }})
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run deploy jobspark-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/jobspark-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated