name: CI/CD to Cloud Run Jobspark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ env.PROJECT_ID }}
  SERVICE_NAME: Jobspark-api
  REGION: asia-southeast2

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/jobspark-api:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/jobspark-api:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy jobspark-api \
          --image gcr.io/${{ env.PROJECT_ID }}/jobspark-api:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticate