name: Build and Deploy to Cloud Run CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_ID: jobspark
  SERVICE_NAME: jobspark-api
  REGION: us
  GAR_LOCATION: asia-southeast2
  REPOSITORY: gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Add permissions for GitHub OIDC token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Docker Auth
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Create environment file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

    - name: Build and Push Container
      env:
        IMAGE_NAME: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.GAR_LOCATION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        flags: '--allow-unauthenticated'

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}